// <auto-generated />
using LampWebStore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LampWebStore.Migrations
{
    [DbContext(typeof(LampsContext))]
    [Migration("20191102075204_AddingAuthStuff")]
    partial class AddingAuthStuff
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LampWebStore.Models.Lamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cost");

                    b.Property<string>("ImageRef");

                    b.Property<byte>("LampType");

                    b.Property<string>("Manufacturer");

                    b.HasKey("Id");

                    b.ToTable("Lamps");

                    b.HasData(
                        new { Id = 1, Cost = 16.0, ImageRef = "https://avatars.mds.yandex.net/get-mpic/1767083/img_id4205890578895788084.jpeg/9hq", LampType = (byte)2, Manufacturer = "Philips" },
                        new { Id = 2, Cost = 2.0, ImageRef = "https://avatars.mds.yandex.net/get-mpic/1045304/img_id688239816713013197.jpeg/9hq", LampType = (byte)1, Manufacturer = "OSRAM" },
                        new { Id = 3, Cost = 4.5, ImageRef = "https://avatars.mds.yandex.net/get-mpic/1045304/img_id5760657839941547295.jpeg/9hq", LampType = (byte)2, Manufacturer = "OSRAM" },
                        new { Id = 4, Cost = 2.4, ImageRef = "https://avatars.mds.yandex.net/get-mpic/1045304/img_id4656031640183289008.jpeg/9hq", LampType = (byte)1, Manufacturer = "Camelion" },
                        new { Id = 5, Cost = 2.7, ImageRef = "https://avatars.mds.yandex.net/get-mpic/1045304/img_id4827177099789801154.jpeg/9hq", LampType = (byte)2, Manufacturer = "Gauss" },
                        new { Id = 6, Cost = 0.5, ImageRef = "https://avatars.mds.yandex.net/get-mpic/1045304/img_id2657193580316822485.jpeg/9hq", LampType = (byte)0, Manufacturer = "Philips" }
                    );
                });

            modelBuilder.Entity("LampWebStore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Login");

                    b.Property<string>("PasswordHash");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, Email = "admin@lampstore.com", Login = "admin", PasswordHash = "AQAAAAEAACcQAAAAEF4i/eAtSYlRrX3AHsd5q68ph4DcZw5eaz3uSvHeCbslVNE5JHCZNwBZaFvKOcDZDA==" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
